### ISSUE TITLE
the nameSrv address is hard code

### ISSUE THREAD

**Issue by leiwangouc** [chebacca/nifi-external-bundle#1]

**Comment by leiwangouc** [comment]
I am using  nifi and and want to publish  flowfile content to rocketMQ
There's some issues about the code:

1  the nameSrv address is hard coded
2   getLogger().error  is used, although there's no error
3  only GetRocketMQ， can PutToRocketMQ  be added?

**Comment by Sun-Xingbin** [comment]
@leiwangouc 

I will fix them next time. 

`PutToRocketMQ` is still in development, maybe a month later

**Comment by leiwangouc** [comment]
It is not difficult to change
I have fixed it and write a simple  PutRocktMQ processor.

Perhaps we can write it  together.

**Comment by Sun-Xingbin** [comment]
Maybe you can create a merge request.

**Comment by Sun-Xingbin** [comment]
fixed
